### ISSUE TITLE
TexView not appear when children only have one TeXViewContainer

### ISSUE THREAD

**Issue by IhwanID** [shah-xad/flutter_tex#54]
Hi @shah-xad, I'm facing a problem when I want to display only one TeXViewContainer in children. when I make the children are two TeXViewContainer, the widget appears smooth.

**Comment by shah-xad** [comment]
I didn't find this issue, can you show how to reproduce this issue.?
BTW I have updated the package please take a look at 3.6.2. Be careful there are some API changes with some new features please do check Changelog and example before proceeding.

**Comment by IhwanID** [comment]
Thanks for answering. 

this code is not working for displaying math syntaxes.

```
TeXView(
              renderingEngine: TeXViewRenderingEngine.katex(),
              children: [
                TeXViewContainer(id: "container_0", children: [
                  TeXViewTeX(
                    r"<h3>Quadratic Equation</h3>",
                    style: TeXViewStyle(
                      textAlign: TeXViewTextAlign.Center,
                      backgroundColor: Colors.red,
                      contentColor: Colors.white,
                    ),
                    id: "tex_0",
                  ),
                  TeXViewTeX(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                      style: TeXViewStyle.fromCSS(
                          "color:white;background-color:green;padding:20px"),
                      id: "tex_1"),
                ]),
              ],
              style: TeXViewStyle(
                margin: TeXViewMargin.all(20),
                elevation: 10,
                borderRadius: TeXViewBorderRadius.all(20),
                border: TeXViewBorder.all(
                  TeXViewBorderDecoration(
                      borderColor: Colors.blue,
                      borderStyle: TeXViewBorderStyle.Solid,
                      borderWidth: 5),
                ),
                backgroundColor: Colors.white,
              ),
              loadingWidget: Center(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    CircularProgressIndicator(),
                    Text("Rendering with ")
                  ],
                ),
              ),
              onTap: (childID) {
                print("TeXView $childID is tapped.");
              }),
```

but when i add more TeXViewContainer in TeXView children. it will works. but i just need single child for the TeXView children. 

```
TeXView(
              renderingEngine: TeXViewRenderingEngine.katex(),
              children: [
                TeXViewContainer(id: "container_0", children: [
                  TeXViewTeX(
                    r"<h3>Quadratic Equation</h3>",
                    style: TeXViewStyle(
                      textAlign: TeXViewTextAlign.Center,
                      backgroundColor: Colors.red,
                      contentColor: Colors.white,
                    ),
                    id: "tex_0",
                  ),
                  TeXViewTeX(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                      style: TeXViewStyle.fromCSS(
                          "color:white;background-color:green;padding:20px"),
                      id: "tex_1"),
                ]),
                TeXViewContainer(id: "container_0", children: [
                  TeXViewTeX(
                    r"<h3>Quadratic Equation</h3>",
                    style: TeXViewStyle(
                      textAlign: TeXViewTextAlign.Center,
                      backgroundColor: Colors.red,
                      contentColor: Colors.white,
                    ),
                    id: "tex_0",
                  ),
                  TeXViewTeX(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                      style: TeXViewStyle.fromCSS(
                          "color:white;background-color:green;padding:20px"),
                      id: "tex_1"),
                ]),
              ],
              style: TeXViewStyle(
                margin: TeXViewMargin.all(20),
                elevation: 10,
                borderRadius: TeXViewBorderRadius.all(20),
                border: TeXViewBorder.all(
                  TeXViewBorderDecoration(
                      borderColor: Colors.blue,
                      borderStyle: TeXViewBorderStyle.Solid,
                      borderWidth: 5),
                ),
                backgroundColor: Colors.white,
              ),
```

**Comment by IhwanID** [comment]
still having some issues with new version of the package. @shah-xad 

this code will not display anything (loading only) because the children of TeXViewColumn is only one.
```
TeXView(
              showLoadingWidget: true,
              renderingEngine: TeXViewRenderingEngine.katex(),
              children: [
                TeXViewInkWell(
                  id: "id_0",
                  child: TeXViewColumn(children: [
                    TeXViewDocument(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                        style: TeXViewStyle.fromCSS(
                            'padding: 15px; color: white; background: green')),
                  ]),
                )
              ],
              style: TeXViewStyle(
                elevation: 10,
                borderRadius: TeXViewBorderRadius.all(25),
                border: TeXViewBorder.all(TeXViewBorderDecoration(
                    borderColor: Colors.blue,
                    borderStyle: TeXViewBorderStyle.Solid,
                    borderWidth: 5)),
                backgroundColor: Colors.white,
              ),
              loadingWidget: Center(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    CircularProgressIndicator(),
                    Text("Rendering...")
                  ],
                ),
              ),
              onTap: (childID) {
                print("TeXView $childID is tapped.");
              }),
```

but when i add more child in children of TeXViewColumn, it will display fine:
```
TeXView(
              showLoadingWidget: true,
              renderingEngine: TeXViewRenderingEngine.katex(),
              children: [
                TeXViewInkWell(
                  id: "id_0",
                  child: TeXViewColumn(children: [
                    TeXViewDocument(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                        style: TeXViewStyle.fromCSS(
                            'padding: 15px; color: white; background: green')),
                    TeXViewDocument(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                        style: TeXViewStyle.fromCSS(
                            'padding: 15px; color: white; background: green')),
                  ]),
                )
              ],
              style: TeXViewStyle(
                elevation: 10,
                borderRadius: TeXViewBorderRadius.all(25),
                border: TeXViewBorder.all(TeXViewBorderDecoration(
                    borderColor: Colors.blue,
                    borderStyle: TeXViewBorderStyle.Solid,
                    borderWidth: 5)),
                backgroundColor: Colors.white,
              ),
              loadingWidget: Center(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    CircularProgressIndicator(),
                    Text("Rendering...")
                  ],
                ),
              ),
              onTap: (childID) {
                print("TeXView $childID is tapped.");
              }),
```

**Comment by shah-xad** [comment]
Sorry for the inconvenience. You were right but now it has been fixed. please upgrade your package to `3.6.2+1`.

**Comment by IhwanID** [comment]
Thank you brother. i will check it :)

**Comment by IhwanID** [comment]
have tried new version (3.6.2+1) but still the widget TexView keep rendering
here's the code

```
TeXView(
              showLoadingWidget: true,
              renderingEngine: TeXViewRenderingEngine.katex(),
              children: [
                TeXViewDocument(r"""<h2>Flutter \( \rm\\TeX \)</h2>""",
                    style: TeXViewStyle(textAlign: TeXViewTextAlign.Center)),
              ],
              style: TeXViewStyle(
                elevation: 10,
                borderRadius: TeXViewBorderRadius.all(25),
                border: TeXViewBorder.all(TeXViewBorderDecoration(
                    borderColor: Colors.blue,
                    borderStyle: TeXViewBorderStyle.Solid,
                    borderWidth: 5)),
                backgroundColor: Colors.white,
              ),
              loadingWidget: Center(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    CircularProgressIndicator(),
                    Text("Rendering...")
                  ],
                ),
              ),
              onTap: (childID) {
                print("TeXView $childID is tapped.");
              }),
```

**Comment by shah-xad** [comment]
Do you have anything in the logs? because it's working perfectly here.
I am using `Channel beta, 1.18.0-11.1.pre` I'll test it in stable.

**Comment by shah-xad** [comment]
I just tested in stable and everything is working fine.
Did you try to clean your project?

**Comment by IhwanID** [comment]
oh I see. I guess you only tried it in Android Device and I only tried in iOS Device 😄. 

I have tried both just now. working perfectly in Android Device but not for the iOS Device. 

this is ios logs:

```
flutter: Server running on http://localhost:5353
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5353/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?port=5353&instanceCount=1&configurations=\"{}\"&urlRawTeXHTML=%7B%22meta%22%3A%7B%22type%22%3A%22tex-view%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22root%22%7D%2C%22id%22%3Anull%2C%22data%22%3A%5B%7B%22meta%22%3A%7B%22type%22%3A%22tex-view-ink-well%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22internal_child%22%7D%2C%22id%22%3A%22id_0%22%2C%22data%22%3A%7B%22meta%22%3A%7B%22type%22%3A%22tex-view-column%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22internal_children%22%7D%2C%22data%22%3A%5B%7B%22meta%22%3A%7B%22type%22%3A%22tex-view-document%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22leaf%22%7D%2C%22data%22%3A%22%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20<…>
```
 Hopefully it's can work well in both device

**Comment by shah-xad** [comment]
Yeah I didn't try it on iOS as I don't have MAC this time. Just let me know if this example works fine?

```
TeXView(
              showLoadingWidget: true,
              renderingEngine: TeXViewRenderingEngine.katex(),
              children: [
                TeXViewInkWell(
                  id: "id_0",
                  child: TeXViewColumn(children: [
                    TeXViewDocument(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                        style: TeXViewStyle.fromCSS(
                            'padding: 15px; color: white; background: green')),
                    TeXViewDocument(r"""<p>                                
                           When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                           $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                        style: TeXViewStyle.fromCSS(
                            'padding: 15px; color: white; background: green')),
                  ]),
                )
              ],
              style: TeXViewStyle(
                elevation: 10,
                borderRadius: TeXViewBorderRadius.all(25),
                border: TeXViewBorder.all(TeXViewBorderDecoration(
                    borderColor: Colors.blue,
                    borderStyle: TeXViewBorderStyle.Solid,
                    borderWidth: 5)),
                backgroundColor: Colors.white,
              ),
              loadingWidget: Center(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    CircularProgressIndicator(),
                    Text("Rendering...")
                  ],
                ),
              ),
              onTap: (childID) {
                print("TeXView $childID is tapped.");
              }),
```

**Comment by IhwanID** [comment]
sure that's code working well in iOS Device, but if I remove the one of duplicate children in TeXViewColumn (make the TeXViewColumn have only one single child) the code keep rendering (loading only) and this is the logs:

```
[VERBOSE-2:shell.cc(213)] Dart Error: Unhandled exception:
PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5353/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?port=5353&instanceCount=1&configurations=\"{}\"&urlRawTeXHTML=%7B%22meta%22%3A%7B%22type%22%3A%22tex-view%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22root%22%7D%2C%22id%22%3Anull%2C%22data%22%3A%5B%7B%22meta%22%3A%7B%22type%22%3A%22tex-view-ink-well%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22internal_child%22%7D%2C%22id%22%3A%22id_0%22%2C%22data%22%3A%7B%22meta%22%3A%7B%22type%22%3A%22tex-view-column%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22internal_children%22%7D%2C%22data%22%3A%5B%7B%22meta%22%3A%7B%22type%22%3A%22tex-view-document%22%2C%22tag%22%3A%22div%22%2C%22node%22%3A%22leaf%22%7D%2C%22data%22%3A%22%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%2<…>
```

**Comment by shah-xad** [comment]
Ok I got it. Just upgrade to `3.6.2+2` and let me know.

**Comment by IhwanID** [comment]
the newest version of this package `3.6.2+2` is working fine & well both in Android & iOS. Thanks, sir. you're really a hero.
